### ISSUE TITLE
Manage iOS8 UIActionSheet deprecation

### ISSUE THREAD

**Issue by shouze** [intentkit/IntentKit#45]
As exposed here:
http://nshipster.com/uialertcontroller/?utm_campaign=iOS_Dev_Weekly_Issue_166&utm_medium=email&utm_source=iOS%2BDev%2BWeekly

**Comment by lazerwalker** [comment]
I'm going to close this, since I don't believe it's a practical concern. Happy to reopen if anyone feels otherwise.
