### ISSUE TITLE
Demo app can't compile

### ISSUE THREAD

**Issue by markfulo** [intentkit/IntentKit#51]
These are the errors:

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

I also tried to update the pod but it also has an error:

NoMethodError - undefined method `[]' for #<Xcodeproj::Project::Object::PBXFileReference:0x007f8249322260>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/project.rb:186:in `block in add_file_reference'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `block in each_filename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each_filename'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/project.rb:184:in `add_file_reference'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:168:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:166:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:166:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:162:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:162:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:104:in `block in add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:102:in `add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:38:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:486:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:130:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:128:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:96:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by lazerwalker** [comment]
Hmm. Wouldn't surprise me if that's an issue related to all of the recent changes in CocoaPods and the release of 0.36. I'm hoping I'll have the time to check this out soon – thanks!

**Comment by markfulo** [comment]
Alright! hopefully you can fix it, Thanks! :+1:

**Comment by lazerwalker** [comment]
This is potentially a CocoaPods 0.36 issue – see the reference directly above this comment for #3195.

**Comment by kylef** [comment]
@lazerwalker This appears to be a problem with your pod spec, you have the same resources used across multiple resource and resource bundles.

Commenting out `ss.resources = 'IntentKit/IntentKit-Localizations.bundle'` from your pod spec will make it work.

You'll notice that `'IntentKit' => 'IntentKit/{**/*.strings,Images/*.png}'` matches the .string files inside the `IntentKit/IntentKit-Localizations.bundle` so they are included multiple times.

**Comment by lazerwalker** [comment]
@kylef that (sadly!) doesn't seem to be solving the problem :scream_cat:  

I commented out that single line (and after a once-over of the rest of the podspec, it looks like there shouldn't be any other such duplications) and I'm still getting the exact same error / stack trace with a clean pod install.

**Comment by lazerwalker** [comment]
Nope, hold the phone. The pod was getting cached – after inserting foot firmly in mouth, seems to be working great.

Thanks!

**Comment by lazerwalker** [comment]
@markfulo Before I push a new build, any chance you can confirm this fix by checking out HEAD?

**Comment by markfulo** [comment]
@lazerwalker, I have build it now and it's working. Thanks a lot! but there's seems to be 3 issues with the shell script:
- find: 2/IntentKit/Apps: No such file or directory
- find: 2/IntentKit/Images: No such file or directory
- Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by lazerwalker** [comment]
Sorry I hadn't gotten back to you about this. Did you ever figure it out? 

I've been mucking around with the test project for code coverage stuff, and it seems to be working fine for me, but happy to help troubleshoot if you're still having issues.

**Comment by lazerwalker** [comment]
Ping? Going to close this for now, but happy to reopen / help if you're still having issues.
