### ISSUE TITLE
Safari doesn't show up on INKBrowserHandler

### ISSUE THREAD

**Issue by pedro380085** [intentkit/IntentKit#54]
The following code (which is outdated on the README):

```
    NSURL *url = [NSURL URLWithString:@"http://google.com"];
    INKBrowserHandler *browserHandler = [[INKBrowserHandler alloc] init];
    INKActivityPresenter *presenter = [browserHandler openURL:url];
    [presenter presentActivitySheetFromViewController:self
                                      popoverFromRect:CGRectZero
                                               inView:self.view
                             permittedArrowDirections:UIPopoverArrowDirectionAny
                                             animated:YES completion:nil];
```

Doesn't show Safari as an option. Why?

Thanks,

**Comment by lazerwalker** [comment]
Hey! As you can tell, I'm clearing through old issues :)

I'm guessing you either figured this out and/or moved on, but on the off-chance you didn't, you want to set the handler's `showFirstPartyApp` option (http://cocoadocs.org/docsets/IntentKit/0.7.3/Classes/INKHandler.html#//api/name/showFirstPartyApp) to `YES`/`true`.
