### ISSUE TITLE
iOS 9 broke the application picker

### ISSUE THREAD

**Issue by asalom** [intentkit/IntentKit#60]
After updating to iOS 9, IntentKit can't find other alternatives to the default application.
Let's say I want to present the Map Handler on my iPhone with both Waze and Google Maps installed.

Having this method called:
```objc
- (void)openMapWithDirectionsFrom:(NSString *)fromString to:(NSString *)toString {
    INKMapsHandler *handler = [INKMapsHandler new];
    INKActivityPresenter *presenter = [handler directionsFrom:fromString to:toString mode:INKMapsHandlerDirectionsModeWalking];
    [presenter presentModallyWithCompletion:^{
        [self.view removeFromSuperview]; 
    }];
}
```

I get the following logs on the console:
```
2015-09-22 12:41:17.185 App[1087:471378] -canOpenURL: failed for URL: "comgooglemaps://" - error: "This app is not allowed to query for scheme comgooglemaps"
2015-09-22 12:41:17.191 App[1087:471378] -canOpenURL: failed for URL: "waze://" - error: "This app is not allowed to query for scheme waze"
```

This is a new feature or bug by Apple. More information can be found [here] (http://awkwardhare.com/post/121196006730/quick-take-on-ios-9-url-scheme-changes).

To let the user choose their favorite mapping service we must add a new key to the Info.plist as follows.
```plist
<key>LSApplicationQueriesSchemes</key>
<array>
	<string>waze</string>
	<string>comgooglemaps</string>
</array>
```

**Comment by gintechsystems** [comment]
It does not seem to work with Apple Maps anymore either?

**Comment by nicolasFernandez** [comment]
running the same problem over here... does anyone find a solution?

**Comment by bocato** [comment]
Running same problem here, is there any solution?

**Comment by lazerwalker** [comment]
@gintechsystems @nicolasFernandez @bocato Have you tried adding the appropriate URL schemes to the appropriate Info.plist key?

With iOS 9, there's no way to avoid having to manually whitelist URL schemes that way. Perhaps it could be automated, rather than requiring you to manually add the schemes, but for now I'm just trying to figure out if there's an IntentKit bug outside of the OS's requirements.

**Comment by bocato** [comment]
I manually whitelisted the URL schemes. Thanks.

**Comment by gintechsystems** [comment]
@bocato what did you do exactly? I believe i tried doing this before and it didnt work for me. Thanks.

**Comment by bocato** [comment]
@gintechsystems I've put the appropriate key on the Info.plist and everything worked as suposed to.
Also, i've changed the way i was instantiating the presenter to the method below.

`INKActivityPresenter *presenter = [mapsHandler directionsFrom:currentLocation to:destination];
    [presenter presentModally];`

**Comment by lazerwalker** [comment]
Gonna close this for now, although perhaps an addition to the README is in order.
