### ISSUE TITLE
duplicate symbols for ink_urlEncode

### ISSUE THREAD

**Issue by lprhodes** [intentkit/IntentKit#63]
Should be changed to:

extern NSString *(^ink_urlEncode)(NSString *);

**Comment by lazerwalker** [comment]
Ack, right you are – I know I've fixed this for individual projects, but must have forgotten to make the change in the actual project.

Feel like throwing a PR together?

**Comment by patrickkempff** [comment]
#66 fixes this.

**Comment by Ewg777** [comment]
@lazerwalker what's about bumping to a new version number?

**Comment by lazerwalker** [comment]
@Ewg777, sorry for the response! 

Traveling now, but will see if I can cut a new version tomorrow.

**Comment by lazerwalker** [comment]
My current net access doesn't seem fast enough to want to let me push a new version to Cocoapods trunk, but there's now a git tag in this repo of `0.7.3`.

Will push that as soon as I'm back in the states. Leaving this issue open until it's made it into Cocoapods trunk proper.

**Comment by lazerwalker** [comment]
IntentKit 0.7.3 has been pushed to CocoaPods trunk.
