### ISSUE TITLE
pod "IntentKit/Maps" does show Google Maps

### ISSUE THREAD

**Issue by ptejas26** [intentkit/IntentKit#64]
After integrating the library with a project, It does not show Google Maps though it is installed in the iPhone.** The Library works perfectly fine in iPad showing both native "Apple Maps" and Installed Google Maps. **. Hope you people can track this issue and find its solution.

**Comment by lazerwalker** [comment]
Thanks for this! I'm afraid I've been a bit of an absentee maintainer as of late – don't think there are too many folks using this in a post-iOS 9 world.

A question for you: have you explicitly declared the Google Maps URL scheme in your Info.plist file?

**Comment by lazerwalker** [comment]
Ping @ptejas26! Would be interested to know either if you've figured this out, or if it's still happening if you've declared the URL scheme in your info.plist.

**Comment by JAStanton** [comment]
@lazerwalker you're absolutely right. I had the exact issue and I added google maps url scheme to my info.plist like so:
```
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>comgooglemaps</string>
		<string>comgooglemaps-x-callback</string>
		<string>mybundleidhere</string>
	</array>
```

For iOS9 users the `canOpenURL` is restricted.  I actually found this documentation here: https://github.com/googlemaps/OpenInGoogleMaps-iOS#supporting-ios-9 which is a similar repo but just focused on google maps.

**Comment by JAStanton** [comment]
Adding these to the docs would probably help eliminate some confusion :)

**Comment by lazerwalker** [comment]
Yeah, great point. Now that I've got confirmation this actually fixes the problem, this should definitely be added to the docs.

I'll add it to my list of things to do, but feel free to throw together a PR yourself if you'd prefer.

**Comment by lazerwalker** [comment]
Some very basic documentation has been added to the README: https://github.com/intentkit/IntentKit/commit/048bf3fa2d57d15bf0176039880d3197476fbecc

Definitely not the ideal solution, but at least people have some warning now.
