### ISSUE TITLE
UIView+MWLayoutHelpers.h

### ISSUE THREAD

**Issue by qing-song** [intentkit/IntentKit#67]
'UIView+MWLayoutHelpers.h' file not found with <angled> include;use"quotes" instead

I have fill with quotes and it does not work.

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by lazerwalker** [comment]
Hi! Sorry, just noticing this now.

I'm guessing you closing this means you figured it out?
