### ISSUE TITLE
NSString+Helpers - NSArray to va_list arguments and string format XCode 8

### ISSUE THREAD

**Issue by pgawlowski** [intentkit/IntentKit#75]
- (id)stringWithFormat:(NSString _)format array:(NSArray_)arguments
  {
  NSRange range = NSMakeRange(0, [arguments count]);
  NSMutableData\* data = [NSMutableData dataWithLength:sizeof(id) \* [arguments count]];
  [arguments getObjects:(__unsafe_unretained id *)data.mutableBytes range:range];
  
  NSString\* result = [[NSString alloc] initWithFormat:format arguments:data.mutableBytes];
  return result;
  }

Since update to xcode 8, I'm receiving EXC_BAD_ACCESS. 

It may be connected with problem that some values passed in array are NSTaggedPointerString \* but I'm not sure. Any ideas?

**Comment by lazerwalker** [comment]
Can you point to where this is? Running a quick ack search over the codebase, I'm not seeing this definition of `stringWithFormat:`, and the only code that's actually calling `stringWithFormat:` as an API consumer are testing tools (Specta / Expecta / OCMockito). 

(Anecdotally, I've been able to ship apps on the App Store using Xcode 8 and IntentKit, but obviously that one data point doesn't mean there isn't a problem)

**Comment by pgawlowski** [comment]
Forgive me my mistake I copy&pasted my own category method which is equal to IntentKit one.

The method I wanted to show is this one from NSString+Helpers:

```
+ (id)stringWithFormat:(NSString *)format array:(NSArray*)arguments; {
    NSRange range = NSMakeRange(0, [arguments count]);
    NSMutableData* data = [NSMutableData dataWithLength:sizeof(id) * [arguments count]];
    [arguments getObjects:(__unsafe_unretained id *)data.mutableBytes range:range];
    NSString* result = [[NSString alloc] initWithFormat:format arguments:data.mutableBytes];
    return result;
}
```

As I wrote before - the problem seems to appear with NSTaggedPointerString \* however I had no time to evaluate this. I will do research and share results as soon as possible.

**Comment by pgawlowski** [comment]
Ok the problem seems to be not connected with NSTaggedPointerString*
My format is 

> /services/user-settings/user/%@?

and the arguments I tested were NSString/NSCFConstantString every single time it ended with EXC_BAD_ACCESS. It was tested on IntentKit version of category with same effect.

**Comment by pgawlowski** [comment]
Ok, my fault. It's just caused by arm64. After updating xcode to xcode 8 I accidentally changed simulator from iPad2 to iPadAir.

**Comment by ayansg** [comment]
Just for my own learning purpose, does your category method works for basic types like int, char, double, etc?

**Comment by pgawlowski** [comment]
Oh, hard to say. It's been a while since I used it. Just try ;)
